os:
  - linux
rvm:
  - 2.3.0
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - rbx
matrix:
  include:
  - os: osx
    # XCode 7.3 -> OS X 10.11
    osx_image: xcode7.3
    rvm: system
  - os: osx
    # XCode 7.1 -> OS X 10.10
    osx_image: xcode7.1
    rvm: system
bundler_args: --jobs=1 --retry=3
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install git-svn ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem update bundler ; fi
after_success:
  - bundle exec rake binary
